name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Initialize the project for Android
      run: |
        npm config set target_os android
        npm config set target_arch arm64
        npm run init
        
    - name: Build Android APK
      run: |
        npm run build -- --target_os=android --target_arch=arm64
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: brave-android-apk
        path: src/out/Default/apks/*.apk 